FROM python:3.9-slim-buster

RUN apt-get update && \
    apt-get install -y git gcc libpq-dev
    

RUN python -m virtualenv dbt_venv && source dbt_venv/bin/activate && \
    pip install --no-cache-dir -r dbt-requirements.txt && deactivate

COPY ../../  /

WORKDIR /dbt

CMD /dbt/start.sh
